-- Weather Observations Station 5
SELECT TOP 1 CITY, LEN(CITY) AS CITY_LENGTH
FROM STATION
ORDER BY LEN(CITY), CITY;

SELECT TOP 1 CITY, LEN(CITY) AS CITY_LENGTH
FROM STATION
ORDER BY LEN(CITY) DESC, CITY;